CREATE TABLE IF NOT EXISTS "catalog"
(
    id    SERIAL PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    prise VARCHAR(254) NOT NULL ,
    image VARCHAR(50)  NOT NULL
);
 CREATE TABLE IF NOT EXISTS "customer"
(id    SERIAL PRIMARY KEY ,
 name  VARCHAR(200) NOT NULL ,
 lastname VARCHAR(254) NOT NULL ,
 email  VARCHAR(50)  NOT NULL);

CREATE TABLE IF NOT EXISTS "employees"
(id    SERIAL PRIMARY KEY ,
 name  VARCHAR(200) NOT NULL ,
 lastname VARCHAR(254) NOT NULL);

CREATE TABLE IF NOT EXISTS "order"
(id    SERIAL PRIMARY KEY ,
 name  VARCHAR(200) NOT NULL ,
 lastname VARCHAR(254) NOT NULL ,
 address  VARCHAR(50)  NOT NULL);